name: Config Replacement Workflow

on:
  push:
    branches:
      - main

jobs:
  replace-config-values:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Replace config values
        run: |
          jq --arg new_mongo_uri "dummy_mongo_uri" --arg new_jwt_secret "dummy_jwt_secret" \
            '.mongoURI = $new_mongo_uri | .jwtSecret = $new_jwt_secret' \
            config/default.json > config/default_modified.json
          mv config/default_modified.json config/default.json

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -a -m "Replace config values"
          git push
